Locale: en
CompatibilityMode: true
SinkRateTicks: 20
SinkCheckTicks: 100
PilotTool: 280
WorldGuardBlockMoveOnBuildPerm: true
WorldGuardBlockSinkOnPVPPerm: true
ManOverBoardTimeout: 30
RequireCreatePerm: false
DisableCrates: false