Locale: en
CompatibilityMode: true
SinkRateTicks: 20
SinkCheckTicks: 100
TracerRateTicks: 5
PilotTool: 280
WorldGuardBlockMoveOnBuildPerm: true
WorldGuardBlockSinkOnPVPPerm: true
ManOverBoardTimeout: 30
FireballLifespan: 6
FireballPenetration: true
DisableSpillProtection: false
RequireCreatePerm: false
TNTContactExplosives: true
DisableCrates: false
FadeWrecksAfter: 0